// Studies/24.3.31/rest-and-db/Frontend/src/Components/ProductsArea/AddProduct/AddProduct.tsx
import axios from "axios";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router-dom";
import ProductModel from "../../../Models/ProductModel";
import appConfig from "../../../Utils/AppConfig";
import "./AddProduct.css";

function AddProduct(): JSX.Element {

    const navigate = useNavigate();
    const { register, handleSubmit } = useForm<ProductModel>();

    async function submit(product: ProductModel) {
        try {
            const response = await axios.post<ProductModel>(appConfig.productsUrl, product);
            alert("Product has been added. ID: " + response.data.id);
            navigate("/products");
        }
        catch (err: any) {
            alert(err.message);
        }
    }

    return (
        <div className="AddProduct Box">

            <form onSubmit={handleSubmit(submit)}>

                <label>Name:</label>
                <input type="text" autoFocus {...register("name")} required />

                <label>Price:</label>
                <input type="number" step="0.01" {...register("price")} required min="0" max="1000" />

                <label>Stock:</label>
                <input type="number" {...register("stock")} required min="0" max="1000" />

                <button>Add</button>

            </form>
        </div>
    );
}

export default AddProduct;

// Studies/24.3.10/Angular/Northwind/src/app/components/products-area/add-product/add-product.component.ts
import { Component } from '@angular/core';
import { ProductModel } from '../../../models/product.model';
import { FormsModule } from '@angular/forms';
import { ProductsService } from '../../../services/products.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-add-product',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './add-product.component.html',
  styleUrl: './add-product.component.css',
})
export class AddProductComponent {
  public product = new ProductModel();

  constructor(
    private productsService: ProductsService,
    private router: Router
  ) {}

  public async send() {
    try {
      await this.productsService.addProduct(this.product);
      alert('Product has been added ');
      // this.router.navigate(['/products']);
      this.router.navigateByUrl('/products');
      console.log(this.product);
    } catch (error: any) {
      console.log(error.message);
    }
  }
}

<div>
  <form>
    <label>Name:</label>
    <input type="text" name="name" [(ngModel)]="product.name" />

    <label>Price:</label>
    <input type="number" name="price" [(ngModel)]="product.price" />

    <label>Stock:</label>
    <input type="number" name="stock" [(ngModel)]="product.stock" />

    <label>Image:</label>
    <input type="file" />

    <button (click)="send()">Add product</button>
  </form>
</div>
